name: Compile LaTeX and Make Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}
        path: main.pdf
