name: Compile LaTeX and Make Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        compiler: pdflatex
        args: >
          -synctex=1
          -interaction=nonstopmode
          -file-line-error
          -halt-on-error
          main.tex
          %;
          makeglossaries %
          biber %
          %;
          pdflatex -synctex=1 -interaction=nonstopmode main.tex
          pdflatex -synctex=1 -interaction=nonstopmode main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: main.pdf
        if-no-files-found: error
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Auto-generated release for tag ${{ github.ref }}
          {% if github.event_name == 'pull_request' %}
          Pull request associated with this release:
          - #{{ github.event.pull_request.number }}: {{ github.event.pull_request.title }} ({{ github.event.pull_request.html_url }})
          {% endif %}
        draft: false
        prerelease: false
        files:
          - name: main
            path: main.pdf
